### ISSUE TITLE
api.met.no traffic limits exceeded

### ISSUE THREAD

**Issue by geira** [ioBroker/ioBroker.yr#119]
**Describe the bug**  
IoBroker exceeds api.met.no traffic limits as stated in Terms of Service

**Additional context**  
I am the sysadmin of the MET Norway Weather API. Our [Terms of Service](https://api.met.no/doc/TermsOfService) states that traffic to api.met.no must not exceed 20 requests per second. At times, ioBroker generates over 1000, generating huge spikes in our traffic:

        2 Mar  1 01:05:55
        2 Mar  1 01:05:57
        2 Mar  1 01:05:59
      177 Mar  1 01:06:00
      523 Mar  1 01:06:01
     1045 Mar  1 01:06:02
      698 Mar  1 01:06:03
      262 Mar  1 01:06:04
      112 Mar  1 01:06:05
      141 Mar  1 01:06:06
       74 Mar  1 01:06:07
       45 Mar  1 01:06:08
       22 Mar  1 01:06:09
       21 Mar  1 01:06:10
       20 Mar  1 01:06:11
       16 Mar  1 01:06:12
       14 Mar  1 01:06:13
        9 Mar  1 01:06:14
        5 Mar  1 01:06:15
        4 Mar  1 01:06:16
        2 Mar  1 01:06:17
        4 Mar  1 01:06:18
        1 Mar  1 01:06:19
        3 Mar  1 01:06:21
        1 Mar  1 01:06:22
        3 Mar  1 01:06:23
        2 Mar  1 01:06:24

As is clearly evident from the statisticks, there appears to be some periodic jobs starting at 6 min over every hour generating massive burst of traffic:

    1049 Mar  1 02:06:02
    1045 Mar  1 01:06:02
     999 Mar  1 03:06:02
     979 Mar  1 04:06:02
     963 Mar  1 05:06:02
     958 Mar  1 00:06:02
     914 Mar  1 07:06:02
     906 Mar  1 08:06:02
     881 Mar  1 06:06:02
     870 Mar  1 11:06:03
     841 Mar  1 11:06:02
     838 Mar  1 10:06:02
     831 Mar  1 10:06:03
     795 Mar  1 08:06:03
     766 Mar  1 03:06:03
     754 Mar  1 07:06:03
     748 Mar  1 00:06:03
     742 Mar  1 05:06:03
     735 Mar  1 06:06:03
     720 Mar  1 09:06:02
     712 Mar  1 04:06:03
     698 Mar  1 01:06:03
     679 Mar  1 02:06:03
     662 Mar  1 09:06:03
     554 Mar  1 09:06:04
     528 Mar  1 05:06:01
     523 Mar  1 01:06:01
     520 Mar  1 08:06:01
     519 Mar  1 02:06:01
     515 Mar  1 04:06:01
     510 Mar  1 07:06:01
     508 Mar  1 00:06:01
     497 Mar  1 06:06:01
     487 Mar  1 03:06:01
     451 Mar  1 10:06:01
     436 Mar  1 06:06:04
     429 Mar  1 11:06:04
     425 Mar  1 09:06:01
     406 Mar  1 11:06:01
     377 Mar  1 10:06:04
     355 Mar  1 07:06:04
     347 Mar  1 04:06:04
     325 Mar  1 05:06:04
     322 Mar  1 03:06:04
     308 Mar  1 02:06:04
     308 Mar  1 00:06:04
     296 Mar  1 08:06:04
     283 Mar  1 09:06:05
     262 Mar  1 01:06:04
     199 Mar  1 11:06:05

In total, your traffic averages around 7500 requests per hour, which is fine. The problem is that a lot of it appears simultaneously, potentially affecting other users. As is stated in the TOS:

> **Don't schedule many requests at the same time, e.g. every hour on the dot or when the forecast model runs are finished. Add a random number of minutes to the time of the requests as our data are continously updated. Spread your traffic evenly out over time so it makes a flat curve, not a sawtooth.**

Furthermore, half of the traffic is going to the `/weatherapi/weathericon/2.0/legends` endpoint, which is totally unnecessary. This is a static file that will never be changed unless the icons change. You should download this and bundle it with your application. We will soon remove this endpoint and pack the file inside the icons archive instead.

Finally, note that the TOS explicitly prohibits the use of the Yr trademark and logo in third party applications:

> You are not allowed to make services/sites that appear to be made by Yr, NRK or The Norwegian Meteorological Institute. In other words, you may not use the word "Yr" as a part of your service name, or attach the Yr logo to your service.

To continue using the service, we require you to implement the following measures:

1. Distribute your traffic evenly over time, instead of periodic spikes
2. Instead of contacting api.met.no, we will generate a custom subdomain which you must use for all traffic
3. Remove the requests to `/weatherapi/weathericon/2.0/legends` 
4. Stop using the Yr logo and trademark in the application. ioBroker/metno would be fine

**Comment by Apollon77** [comment]
Thank you for your report, we will try to reach the users to better split their execution times because the traffic comes not from a central place :-(

We will also check on the other infos you wrote.

I'm very sorry for the inconvenience :-(

**Comment by Apollon77** [comment]
@geira I thinkit would be best to communicate via emailf or the official stuff: Can you give us an email? ALternatively please send us an email to ingo.fischer@iobroker.net and info@iobroker.net Thank you

**Comment by geira** [comment]
Please send an email to weatherapi-adm@met.no, then it'll end up in our ticket system.

**Comment by Apollon77** [comment]
We will sync internally and come up with an action plan on how to adress the topic in an email to you

**Comment by geira** [comment]
Just open a ticket and I will send you some suggestions.

**Comment by Apollon77** [comment]
E-Mail sent yesterday afternoon

**Comment by Apollon77** [comment]
@geira I have released a new version with reduced calls and to automatically move start time for the users just some minutes ago and We also enabled communication to all users of the adapter ... so I would expect the requests to spread better starting soon.

**Comment by Apollon77** [comment]
@geira The update is out in the meantime to >40% of the users ... do you already see the traffic distribute better?

**Comment by geira** [comment]
Seems to be helping, now only 25% of traffic is coming at XX:06. Still spikes at over 400 req/s though.

**Comment by Apollon77** [comment]
@geira SHould get better when version distributes more ...
![Bildschirmfoto 2022-03-21 um 13 39 11](https://user-images.githubusercontent.com/11976694/159262607-fff1d3b7-cfd9-46c0-97ea-37b871a629d2.png)
(the upper "green" is the relevant one

**Comment by Apollon77** [comment]
For the rest I await your answer to my email

**Comment by Apollon77** [comment]
@geira We would still wait for additional details like the own endpoint you requested us to use ...

**Comment by geira** [comment]
> @geira We would still wait for additional details like the own endpoint you requested us to use ...

I have sent it to you twice in email, as replies to the met.no ticket you created. This is semi-secret, so should be part of configuration and not in a public code repo.

**Comment by Apollon77** [comment]
Fixed in 5.3.0
