### ISSUE TITLE
legend.json

### ISSUE THREAD

**Issue by Thomas-Doc** [ioBroker/ioBroker.yr#123]
Info:

Please reinstall the adapter!
Error while loading Legend data:  ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.yr/legend.json'

Any workaround?

**Comment by Apollon77** [comment]
Yes, wait for update later today

**Comment by Apollon77** [comment]
Or install GitHub version... and give Feedback :-)

**Comment by Thomas-Doc** [comment]
ok, hat funktioniert. Vielen Dank!

Das Log ist jetzt voll mit Meldungen:
This object will not be created in future versions. Please report this to the developer.
| warn | Object yr.0.forecastHourly.213h.time is invalid: Default value has to be type "number" but received type "string"

Ist bestimmt schon bekannt, ich werd dann mal in den nächsten Tagen von github updaten.

**Comment by Apollon77** [comment]
Nee, bisher nicht bekannt ... Bitte mal volles log posten

**Comment by Apollon77** [comment]
... in einem neuen issue bitte! :) und am bestne ein Debug log ( Instanz loglevel auf Debug setzen!)

**Comment by Apollon77** [comment]
Ok, found it ... new version on GitHub, in beta soon
