### ISSUE TITLE
Symbole werden Teilweise nicht richtig angezeit

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.yr#13]
Siehe Screenshot

![grafik](https://cloud.githubusercontent.com/assets/17859549/26519557/92748250-42c3-11e7-8957-fe48ee1f8b37.png)
in diesem Beispiel sind es diese:
http://symbol.yr.no/grafikk/sym/b38/40n.png
http://symbol.yr.no/grafikk/sym/b38/02n.png

Ich denke es liegt an der Webseite. Derzeit werden auf der Webseite andere Symbole angezeigt mit dieser URL:
**http://symbol.yr.no/grafikk/sym/v2016/png/38/** 40n.png

Vielleicht genügt es die Base URL in der yr.js anzupassen.

**Comment by buanet** [comment]
Siehe: https://github.com/ioBroker/ioBroker.yr/pull/12 

Mfg, Andre

**Comment by Apollon77** [comment]
Please test 1.0.6 from GitHub
