### ISSUE TITLE
Einige Felder werden nicht mehr aktualsiert

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.yr#17]
Seit Version 2.01 werden bei mir die beiden Fehler

temperature_max und temperature_min unter day2 in den Objekten nicht mehr aktualisiert.

**Comment by Papi32** [comment]
Das Gleiche habe ich auch.
ioBroker-Log schreibt dennoch: "got weather data from yr.no"

**Comment by Baenker** [comment]
Da ich den Adapter nicht mehr nutze und hier scheinbar nichts mehr passiert mache ich mein Issue zu.
