### ISSUE TITLE
date field not filled

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.yr#18]
The date fild from all 3 days is empty. error invalid date

**Comment by 150d** [comment]
It is not empty, actually: When you use the values in some way you will see that they do indeed contain the correct date.

It's just that the Admin interface for some reason can't display the string and instead outputs "invalid date". I can't figure out why though - the string conforms exactly to the setting in configuration/main settings/date format. It should be correct in every regard.
