### ISSUE TITLE
Update from 2.0.3 -> 3.0.1 TypeError

### ISSUE THREAD

**Issue by lobomau76** [ioBroker/ioBroker.yr#37]
The following message I get after the Update.
Do I have to do anything about the new JSON-API to make it work?

`
<html>
<body>

host.ioBrokerCT | 2021-07-07 13:18:50.865 | error | instance system.adapter.yr.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
yr.0 | 2021-07-07 13:18:49.884 | error | Assignment to constant variable.
yr.0 | 2021-07-07 13:18:49.884 | error | TypeError: Assignment to constant variable. at Yr.main (/opt/iobroker/node_modules/iobroker.yr/main.js:458:27) at Yr.onReady (/opt/iobroker/node_modules/iobroker.yr/main.js:66:14)
yr.0 | 2021-07-07 13:18:49.876 | error | unhandled promise rejection: Assignment to constant variable.
yr.0 | 2021-07-07 13:18:49.874 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by Apollon77** [comment]
Fixed in 3.0.2 since yesterday
