### ISSUE TITLE
Readme not correct at iobroker Admin

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.yr#40]
The Readme is not correct if checking via iobroker:

![grafik](https://user-images.githubusercontent.com/33424168/125574154-3634e7a1-2eb8-46cb-9f1a-635ed2cd4083.png)

At NPM and GIT it is updated but not at Admin.

**Comment by Apollon77** [comment]
if then this is an Admin issue ... it could also be that ther eis some kind of caching involved or such
