### ISSUE TITLE
zuviele Daten 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.yr#41]
schalte ich die Compact Sicht ein in Einstellungen bekomme ich trotzdem alle Daten also auch die 24h 
![grafik](https://user-images.githubusercontent.com/6681528/127430756-73ccdefc-fd44-40ee-805e-662e84c05e4c.png)
![grafik](https://user-images.githubusercontent.com/6681528/127431020-b721df3d-8142-4d99-bf78-59d1bf46d6ff.png)

**Comment by Apollon77** [comment]
Please show debug log ..code wise the parameter compact/complete is sent to the API and then adapter process whatever is the response ... so maybe they return too much?

**Comment by arteck** [comment]
the request is correct
https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=

but

![grafik](https://user-images.githubusercontent.com/6681528/128634285-836bc706-3725-46e5-ac43-9f8444043476.png)

you make this

**Comment by Apollon77** [comment]
What you mean? The adapter processes the data which are returned ... I think in former old API the "compact" version of the response returned less data? Now it seems different.

So what should we  fix? and how?

**Comment by arteck** [comment]
compact is compact .. i do not need more data wehen compact is selected
