### ISSUE TITLE
invalid Date im Object

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.yr#42]
![grafik](https://user-images.githubusercontent.com/6681528/127430813-3b4811ff-e6a6-4081-a64d-6573cbe72795.png)

ist im allen Tagen so

**Comment by Apollon77** [comment]
welche verison? Bitte mal date Objekt löschen, danach korrekt?

**Comment by arteck** [comment]
jetzt hab ich die aktuelle Version3.0.5 geladen.. da fehlt der Tag0 komplett
![grafik](https://user-images.githubusercontent.com/6681528/128634403-0cf20c10-e94d-4d65-93dd-6bec20dd6518.png)

**Comment by Apollon77** [comment]
Jupp yr hat eine neue API, ist aktuell Datentechnisch nicht alles wie vorher ...

**Comment by arteck** [comment]
ich merk schon..

**Comment by Apollon77** [comment]
Still something open here?
