### ISSUE TITLE
State .time wird als String abgelegt

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.yr#67]
Der State **yr.0.forecastHourly.*.time** wird als Type "string" angelegt, enthält aber einen Unix-Timestamp in Millisekunden.
Durch den Typ "string" kann die Zeit in VIS mit dem Widget **TimeStampValue** nicht angezeigt werden.
Daher als Statetyp bitte in "value" umsetzen

**Versions:**  
 - Adapter version: 3.0.5

Danke, Ralf

**Comment by Apollon77** [comment]
State type value gibt es nicht.Wenn müsste es "number" sein

**Comment by RK62** [comment]
Richtig. Ich hatte die Bezeichnung aus der Rolle abgelesen.
Das sollte von String auf Number geändert werden.
