### ISSUE TITLE
div. Parameter werden nicht gefüllt

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.yr#9]
yr.0.forecast.day0.humidity bleibt leer (und Fehler SQL: Object?).

yr.0.forecast.day0.precipitation_chance hat als Wer null.

**Comment by GermanBluefox** [comment]
Immer noch aktuell?

**Comment by darkbrain85** [comment]
Hi!

Sehr alter Bug. Ja, zum heutigen Tag ist es noch aktuell. Ich habe gerade einen Umstieg von Weatherunderground versucht und dabei auch die beiden leeren Eigenschaften gefunden.
