### ISSUE TITLE
instance system.adapter.yr.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by zaphod2** [ioBroker/ioBroker.yr#94]
Hey,
ich habe hier seid gestern "instance system.adapter.yr.0 terminated with code 1 (JS_CONTROLLER_STOPPED)" und ich bekomme es einfach nicht gelöst.
IoB läuft auf einer Proxmox CT alle Adapter sich auf dem neuesten Stand.
Neuinstallation geht nicht, dann sehe ich keine Adapter mehr die neu installiert werden und die Fehlermeldungen bleiben. Ich weiß nicht mehr wo es hängt.

 iobroker debug yr
Debugger listening on ws://127.0.0.1:9229/39d84cde-292e-42b6-9700-c33a0851613f
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /opt/iobroker/node_modules/got/dist/source/index.js
require() of ES modules is not supported.
require() of /opt/iobroker/node_modules/got/dist/source/index.js from /opt/iobroker/node_modules/iobroker.yr/main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/iobroker/node_modules/got/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yr/main.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM' 

 - Adapter version: 5.0.0
 - Node version: 14.18.3

**Comment by Apollon77** [comment]
Ok, honestly ... How you installed this adapter? Could it be that you instaleld via Github  ... and yes this version seesm broken bbecause of an incompatible got version ... but this should NOT affect the notmally released verison 5.0.0 ...

**Comment by zaphod2** [comment]
Ja über github installiert. und auch schon länger erfolgreich im Einsatz, erst seid ein paar tagen kommen die Fehler.

**Comment by Apollon77** [comment]
1.) Bitte Adapter nur über GitHub installieren wenn Du explizot aufgefordert wirst, ansonsten KEIN support!
2.) Komisch weil die Dep hätte von Anfang an alles kaputt machen müssen (ok seit 6 tagen ... also hast du vllt nochmal von GitHub aktualisiert?)

Bitte nuttze die offizielle Beta Version von NPM und mach das IMMER

**Comment by zaphod2** [comment]
Es läuft wieder...
Was hab ich gemacht? keine Ahnung.
Hab neu installiert von github die 5.0.0 version und hab neu gestartet.

**Comment by zaphod2** [comment]
Hab vorsichtshalber von npm neu installiert. Mit der 3.0.5 gab es übrigens bei mir Anzeigeprobleme.

**Comment by Apollon77** [comment]
Auch die 5.0 ist auf NPM und auch demnächst im Stable repo
